version: "3.9"

services:
  plantsindo_db:
    image: postgres:16-alpine
    container_name: plantsindo_postgres

    environment:
      POSTGRES_DB: plantsindo
      POSTGRES_USER: plantsindo
      POSTGRES_PASSWORD: plantsindo

    volumes:
      - plantsindo_pgdata:/var/lib/postgresql/data

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plantsindo -d plantsindo"]
      interval: 5s
      timeout: 5s
      retries: 10

  plantsindo_web:
    build: .

    container_name: plantsindo_container

    command: gunicorn ecom.wsgi:application --bind 0.0.0.0:8031 --workers 3

    volumes:
      - .:/app

    ports:
      - "8031:8031"

    env_file:
      - .env

    environment:
      POSTGRES_DB: plantsindo
      POSTGRES_USER: plantsindo
      POSTGRES_PASSWORD: plantsindo
      POSTGRES_HOST: plantsindo_db
      POSTGRES_PORT: 5432

    depends_on:
      plantsindo_db:
        condition: service_healthy

    restart: unless-stopped

volumes:
  plantsindo_pgdata: