services:

  plantsindo_web:
    build: .

    container_name: plantsindo_container

    command: gunicorn ecom.wsgi:application --bind 0.0.0.0:8031 --workers 3

    volumes:
      - .:/app

    ports:
      - "8031:8031"

    env_file:
      - .env

    environment:
      POSTGRES_DB: plantsindo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: plants@098765
      POSTGRES_HOST: plantsindo_postgres
      POSTGRES_PORT: 5432

    networks:
      - shared_network

    restart: unless-stopped

networks:
  shared_network:
    external: true