# Generated by Django 5.2.11 on 2026-09-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_restore_product_delivery_state_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text='Compact PDP intro line. Falls back to a truncated "description" when blank.',
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="short_tagline",
            field=models.CharField(
                blank=True,
                help_text='Short marketing line shown under the title, e.g. "Compact • Colourful • Perfect for Indoors".',
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="producthighlight",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text='Font Awesome solid icon name without the "fa-" prefix, e.g. "house", "wind", "gear", "seedling".',
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="producthighlight",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Uncheck to hide without deleting.",
            ),
        ),
        migrations.AddField(
            model_name="producthighlight",
            name="title",
            field=models.CharField(
                blank=True,
                help_text='Short heading, e.g. "Perfect for".',
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Falls back to the product name when blank.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("buy_now", "Buy Now"),
                    ("ordered", "Ordered"),
                    ("abandoned", "Abandoned"),
                ],
                db_index=True,
                default="active",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                db_index=True,
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="plant_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("indoor", "Indoor"),
                    ("outdoor", "Outdoor"),
                    ("flowering", "Flowering"),
                ],
                db_index=True,
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sunlight",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_sun", "Full sun"),
                    ("partial", "Partial shade"),
                    ("low_light", "Low light"),
                ],
                db_index=True,
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="watering",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                db_index=True,
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="producthighlight",
            name="text",
            field=models.CharField(
                help_text='Card body, e.g. "Home & Office".', max_length=400
            ),
        ),
    ]
