# Generated by Django 5.2.11 on 2026-09-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_pdp_highlights_tagline_alt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="title",
            field=models.CharField(
                blank=True,
                help_text='Optional caption shown under this thumbnail on the PDP, e.g. "Leaf Detail".',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="variantimage",
            name="title",
            field=models.CharField(
                blank=True,
                help_text='Optional caption shown under this thumbnail on the PDP, e.g. "Leaf Detail".',
                max_length=100,
            ),
        ),
    ]
