from django.urls import path
from . import admin_views
from . import admin_report_views
from . import admin_pot_addon_views
app_name = 'admin_panel'

urlpatterns = [
    path('login/', admin_views.AdminLoginView.as_view(), name='login'),
    path('logout/', admin_views.AdminLogoutView.as_view(), name='logout'),
    path('', admin_views.AdminDashboardView.as_view(), name='dashboard'),
    path('reports/', admin_report_views.ReportsDashboardView.as_view(), name='report_list'),
    path('reports/orders/', admin_report_views.OrdersReportView.as_view(), name='report_orders'),
    path('reports/sales/', admin_report_views.SalesReportView.as_view(), name='report_sales'),
    path('reports/products/', admin_report_views.ProductPerformanceReportView.as_view(), name='report_products'),
    path('reports/customers/', admin_report_views.CustomerReportView.as_view(), name='report_customers'),
    path('reports/inventory/', admin_report_views.InventoryReportView.as_view(), name='report_inventory'),
    path('reports/api/<str:report_type>/', admin_report_views.ReportApiView.as_view(), name='report_api'),
    path('reports/export/<str:report_type>/<str:format_type>/', admin_report_views.ReportExportView.as_view(), name='report_export'),
    path('banners/', admin_views.BannerListView.as_view(), name='banner_list'),
    path('banners/create/', admin_views.BannerCreateView.as_view(), name='banner_create'),
    path('banners/<int:pk>/edit/', admin_views.BannerUpdateView.as_view(), name='banner_edit'),
    path('banners/<int:pk>/delete/', admin_views.BannerDeleteView.as_view(), name='banner_delete'),
    path('categories/', admin_views.CategoryListView.as_view(), name='category_list'),
    path('categories/create/', admin_views.CategoryCreateView.as_view(), name='category_create'),
    path('categories/<int:pk>/edit/', admin_views.CategoryUpdateView.as_view(), name='category_edit'),
    path('categories/<int:pk>/delete/', admin_views.CategoryDeleteView.as_view(), name='category_delete'),
    path('home-categories/', admin_views.HomeCategoryListView.as_view(), name='home_category_list'),
    path('home-categories/create/', admin_views.HomeCategoryCreateView.as_view(), name='home_category_create'),
    path('home-categories/<int:pk>/edit/', admin_views.HomeCategoryUpdateView.as_view(), name='home_category_edit'),
    path('home-categories/<int:pk>/delete/', admin_views.HomeCategoryDeleteView.as_view(), name='home_category_delete'),
    path('deals/', admin_views.DealOfDayListView.as_view(), name='deal_list'),
    path('products/', admin_views.ProductListView.as_view(), name='product_list'),
    path('products/create/', admin_views.ProductCreateView.as_view(), name='product_create'),
    path('products/create-basic/', admin_views.ProductCreateBasicView.as_view(), name='product_create_basic'),
    path('products/<int:pk>/edit/', admin_views.ProductEditView.as_view(), name='product_edit'),
    path('products/<int:pk>/update-basic/', admin_views.ProductUpdateBasicView.as_view(), name='product_update_basic'),
    path('products/<int:pk>/toggle-active/', admin_views.ProductToggleActiveView.as_view(), name='product_toggle_active'),
    path('products/<int:pk>/delete/', admin_views.ProductDeleteView.as_view(), name='product_delete'),
    path('products/<int:pk>/delete-check/', admin_views.ProductDeleteCheckView.as_view(), name='product_delete_check'),
    path('products/<int:pk>/attributes/', admin_views.ProductAttributesListApiView.as_view(), name='product_attributes_list'),
    path('products/<int:pk>/attributes/add/', admin_views.ProductAttributeCreateApiView.as_view(), name='product_attribute_add'),
    path('products/<int:pk>/attributes/reorder/', admin_views.ProductAttributesReorderApiView.as_view(), name='product_attributes_reorder'),
    path('attributes/<int:attr_id>/update/', admin_views.ProductAttributeUpdateApiView.as_view(), name='attribute_update'),
    path('attributes/<int:attr_id>/delete/', admin_views.ProductAttributeDeleteApiView.as_view(), name='attribute_delete'),
    path('attributes/<int:attr_id>/values/add/', admin_views.ProductAttributeValueCreateApiView.as_view(), name='attribute_value_add'),
    path('attributes/<int:attr_id>/values/reorder/', admin_views.ProductAttributeValuesReorderApiView.as_view(), name='attribute_values_reorder'),
    path('attribute-values/<int:av_id>/update/', admin_views.ProductAttributeValueUpdateApiView.as_view(), name='attribute_value_update'),
    path('attribute-values/<int:av_id>/delete/', admin_views.ProductAttributeValueDeleteApiView.as_view(), name='attribute_value_delete'),
    path('products/<int:pk>/variants/', admin_views.ProductVariantsListApiView.as_view(), name='product_variants_list'),
    path('products/<int:pk>/variants/add/', admin_views.VariantCreateApiView.as_view(), name='variant_add'),
    path('variants/<int:variant_id>/update/', admin_views.VariantUpdateApiView.as_view(), name='variant_update'),
    path('variants/<int:variant_id>/delete/', admin_views.VariantDeleteApiView.as_view(), name='variant_delete'),
    path('variants/<int:variant_id>/upload-image/', admin_views.VariantUploadImageView.as_view(), name='variant_upload_image'),
    path('variant-images/<int:image_id>/delete/', admin_views.VariantImageDeleteView.as_view(), name='variant_image_delete'),
    path('variant-images/<int:image_id>/set-primary/', admin_views.VariantImageSetPrimaryView.as_view(), name='variant_image_set_primary'),
    path('variant-images/reorder/', admin_views.VariantImageReorderView.as_view(), name='variant_image_reorder'),
    path('products/<int:product_id>/base-images/upload/', admin_views.ProductImageUploadView.as_view(), name='product_image_upload'),
    path('products/base-images/<int:image_id>/delete/', admin_views.ProductImageDeleteView.as_view(), name='product_image_delete'),
    path('products/base-images/<int:image_id>/set-primary/', admin_views.ProductImageSetPrimaryView.as_view(), name='product_image_set_primary'),
    path('products/base-images/reorder/', admin_views.ProductImageReorderView.as_view(), name='product_image_reorder'),
    path('orders/', admin_views.OrderListView.as_view(), name='order_list'),
    path('orders/<slug:order_number>/', admin_views.OrderDetailView.as_view(), name='order_detail'),
    path('orders/<slug:order_number>/invoice/', admin_views.OrderInvoiceView.as_view(), name='order_invoice'),
    path('orders/<slug:order_number>/update-status/', admin_views.OrderUpdateStatusView.as_view(), name='order_update_status'),
    path('orders/<slug:order_number>/shipment/retry/', admin_views.ShipmentRetryView.as_view(), name='order_shipment_retry'),
    path('orders/<slug:order_number>/shipment/cancel/', admin_views.ShipmentCancelView.as_view(), name='order_shipment_cancel'),
    path('orders/<slug:order_number>/shipment/refresh-tracking/', admin_views.OrderShipmentRefreshTrackingView.as_view(), name='order_shipment_refresh_tracking'),
    path('messages/', admin_views.MessageListView.as_view(), name='message_list'),
    path('messages/<int:pk>/toggle-resolved/', admin_views.MessageToggleResolvedView.as_view(), name='message_toggle_resolved'),
    path('newsletter/', admin_views.NewsletterListView.as_view(), name='newsletter_list'),
    path('upload/s3/', admin_views.S3FileUploadView.as_view(), name='s3_upload'),
    path('reviews/', admin_views.ReviewListView.as_view(), name='review_list'),
    path('reviews/bulk-action/', admin_views.ReviewBulkActionView.as_view(), name='review_bulk_action'),

    # Blog dashboard (custom, not Django admin)
    path('blog/', admin_views.DashboardBlogListView.as_view(), name='blog_list'),
    path('blog/create/', admin_views.DashboardBlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/edit/', admin_views.DashboardBlogUpdateView.as_view(), name='blog_edit'),
    path('blog/<int:pk>/toggle-publish/', admin_views.DashboardBlogTogglePublishView.as_view(), name='blog_toggle_publish'),

    # Reels dashboard (custom, not Django admin)
    path('reels/', admin_views.DashboardReelListView.as_view(), name='reel_list'),
    path('reels/create/', admin_views.DashboardReelCreateView.as_view(), name='reel_create'),
    path('reels/<int:pk>/edit/', admin_views.DashboardReelUpdateView.as_view(), name='reel_edit'),
    path('reels/<int:pk>/toggle-active/', admin_views.DashboardReelToggleActiveView.as_view(), name='reel_toggle_active'),

    # Rental dashboard (custom, not Django admin)
    path('rentals/', admin_views.DashboardRentalListView.as_view(), name='rental_list'),
    path('rentals/bookings/', admin_views.DashboardRentalBookingsView.as_view(), name='rental_bookings'),
    path('rentals/bookings/<int:booking_id>/status/', admin_views.DashboardRentalBookingStatusUpdateView.as_view(), name='rental_booking_status'),
    path('products/<int:pk>/rental-config/', admin_views.ProductRentalConfigUpdateView.as_view(), name='product_rental_config_update'),

    # Combo bundles (first-class Combo model + dashboard CRUD)
    path('combos/', admin_views.DashboardComboListView.as_view(), name='combo_list'),
    path('combos/create/', admin_views.DashboardComboCreateView.as_view(), name='combo_create'),
    path('combos/<int:pk>/edit/', admin_views.DashboardComboUpdateView.as_view(), name='combo_edit'),
    path('combos/<int:pk>/items/', admin_views.ComboBundleItemsListApiView.as_view(), name='combo_items_list'),
    path('combos/<int:pk>/items/add/', admin_views.ComboBundleItemAddApiView.as_view(), name='combo_item_add'),
    path('combos/<int:pk>/candidates/', admin_views.ComboBundleCandidatesApiView.as_view(), name='combo_candidates'),
    path('combo-bundle-items/<int:row_id>/update/', admin_views.ComboBundleItemUpdateApiView.as_view(), name='combo_item_update'),
    path('combo-bundle-items/<int:row_id>/delete/', admin_views.ComboBundleItemDeleteApiView.as_view(), name='combo_item_delete'),
    # Legacy product-flag combo APIs (deprecated; kept for old admin JS if still loaded)
    path('products/<int:pk>/combo-components/', admin_views.ProductComboComponentsListApiView.as_view(), name='product_combo_components_list'),
    path('products/<int:pk>/combo-components/add/', admin_views.ProductComboComponentAddApiView.as_view(), name='product_combo_component_add'),
    path('products/<int:pk>/combo-candidates/', admin_views.ProductComboCandidateProductsApiView.as_view(), name='product_combo_candidates'),
    path('combo-items/<int:row_id>/update/', admin_views.ProductComboComponentUpdateApiView.as_view(), name='product_combo_component_update'),
    path('combo-items/<int:row_id>/delete/', admin_views.ProductComboComponentDeleteApiView.as_view(), name='product_combo_component_delete'),
    # Delivery management URLs
    path('products/<int:pk>/delivery-states/', admin_views.ProductDeliveryStatesUpdateView.as_view(), name='product_delivery_states_update'),
    path('delivery-charges/', admin_views.DeliveryChargesView.as_view(), name='delivery_charges'),
    #Testimonial CRUD URLs
    path('testimonials/', admin_views.TestimonialListView.as_view(), name='testimonial_list'),
    path('testimonials/add/', admin_views.TestimonialCreateView.as_view(), name='testimonial_create'),
    path('testimonials/<int:pk>/', admin_views.TestimonialDeleteView.as_view(), name='testimonial_detail'),
    path('testimonials/<int:pk>/update/', admin_views.TestimonialUpdateView.as_view(), name='testimonial_update'),
    path('testimonials/<int:pk>/delete/', admin_views.TestimonialDeleteView.as_view(), name='testimonial_delete'),
    path('testimonials/<int:pk>/toggle-active/', admin_views.TestimonialToggleActiveView.as_view(), name='testimonial_toggle_active'),

    path('coupons/', admin_views.CouponListView.as_view(), name='coupon_list'),
    path('coupons/create/', admin_views.CouponCreateView.as_view(), name='coupon_create'),
    path('coupons/<int:pk>/edit/', admin_views.CouponUpdateView.as_view(), name='coupon_edit'),
    path('coupons/<int:pk>/toggle-active/', admin_views.CouponToggleActiveView.as_view(), name='coupon_toggle_active'),
    path('coupons/<int:pk>/redemptions/', admin_views.CouponRedemptionListView.as_view(), name='coupon_redemptions'),

    #Pot addons
    path('products/<int:pk>/pot-addons/', admin_pot_addon_views.ProductPotAddonsListApiView.as_view(), name='product_pot_addons_list'),
    path('products/<int:pk>/pot-addons/add/', admin_pot_addon_views.ProductPotAddonAddApiView.as_view(), name='product_pot_addon_add'),
    path('products/<int:pk>/pot-addons/<int:row_id>/delete/', admin_pot_addon_views.ProductPotAddonDeleteApiView.as_view(), name='product_pot_addon_delete'),
    path('products/<int:pk>/pot-addons/reorder/', admin_pot_addon_views.ProductPotAddonReorderApiView.as_view(), name='product_pot_addons_reorder'),
    path('products/<int:pk>/pot-candidates/', admin_pot_addon_views.ProductPotCandidatesApiView.as_view(), name='product_pot_candidates'),
]
